# -*- coding: utf-8 -*-
"""DFC2023-302.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VdTwyQfna1CO4qpUnzFn0pJDpCuWg25p
"""

import cv2
import numpy as np
from google.colab import drive
drive.mount('/content/gdrive')

def save_frame_on_subtitle_change(video_path, subtitle_area, output_folder):
    # Open the video file
    cap = cv2.VideoCapture(video_path)
    prev_frame = None
    frame_count = 0
    saved_frame_count = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Crop the subtitle area from the frame
        subtitle_frame = frame[subtitle_area[1]:subtitle_area[3], subtitle_area[0]:subtitle_area[2]]

        # Convert to grayscale for comparison
        subtitle_gray = cv2.cvtColor(subtitle_frame, cv2.COLOR_BGR2GRAY)

        if prev_frame is None:
            prev_frame = subtitle_gray
            continue

        # Compare the current subtitle frame with the previous one
        difference = cv2.absdiff(prev_frame, subtitle_gray)
        mean_diff = np.mean(difference)

        # If there is a significant difference, save the frame
        if mean_diff > 5:  # Adjust the threshold as needed
            frame_filename = f'{output_folder}/frame_{frame_count:04d}.jpg'
            cv2.imwrite(frame_filename, frame)
            print(f'Saved {frame_filename}')
            saved_frame_count += 1

        prev_frame = subtitle_gray
        frame_count += 1

    cap.release()
    cv2.destroyAllWindows()
    print(f'Total frames saved: {saved_frame_count}')

# Example usage:
video_path = '/content/gdrive/MyDrive/output.mp4'
subtitle_area = (100, 500, 1180, 580)  # Example coordinates (x1, y1, x2, y2)
output_folder = '/content/gdrive/MyDrive/DFC2023'  # Folder where frames will be saved

save_frame_on_subtitle_change(video_path, subtitle_area, output_folder)
